name: Deploy Infrastructure

#on:
#  push:
#    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List root directory
        run: ls -la

      - name: List terraform directory
        run: ls -la terraform || echo "terraform directory not found"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Zip Lambda
        run: |
          ls -la lambda || echo "lambda directory not found"
          cd lambda
          zip -r ../terraform/lambda.zip handler.py
          cd ..

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve


