name: Deploy Infrastructure

#on:
#  push:
#    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # Debug the repo structure
    - name: List root directory
      run: ls -la

    - name: List Terraform directory
      run: ls -la terraform || echo "terraform directory not found"

    - name: List Lambda directory
      run: ls -la lambda || echo "lambda directory not found"

    - name: Check files exist
      run: |
        if [ ! -f lambda/handler.py ]; then
          echo "Missing lambda/handler.py!"
          exit 1
        fi
        if [ ! -d terraform ]; then
          echo "Missing terraform directory!"
          exit 1
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Zip Lambda function
      run: |
        mkdir -p terraform
        zip -j terraform/lambda.zip lambda/handler.py

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve

