name: Deploy Infrastructure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List root directory (debug)
      run: ls -la

    - name: List terraform directory (debug)
      run: ls -la terraform || echo "terraform directory not found"

    - name: List lambda directory (debug)
      run: ls -la lambda || echo "lambda directory not found"

    - name: Check for required files
      run: |
        test -f lambda/handler.py || (echo "Missing lambda/handler.py" && exit 1)
        test -d terraform || (echo "Missing terraform directory" && exit 1)

    - name: Configure AWS credentials (🔴 mock placeholder)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}        # 🔴 Set in GitHub Secrets
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}# 🔴 Set in GitHub Secrets
        aws-region: ${{ secrets.AWS_REGION }}                       # 🔴 Set in GitHub Secrets

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Zip Lambda function
      run: |
        mkdir -p terraform
        zip -j terraform/lambda.zip lambda/handler.py

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve
