name: Deploy Infrastructure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug repo structure
        run: ls -lR

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Zip Lambda function
        run: |
          cd lambda
          zip -r ../terraform/lambda.zip handler.py
          cd ..

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve

