name: Terraform CI/CD

on:
  push:
    branches:
      - main
    # Optional: uncomment to trigger only on TF or Lambda changes
    # paths:
    #   - '**.tf'
    #   - 'lambda.zip'

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (mock for PoC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: FAKEACCESSKEY123       # 🔴 Replace with real key for production
          aws-secret-access-key: FAKESECRETKEY123   # 🔴 Replace with real secret
          aws-region: us-east-1                     # ✅ Matches var.aws_region default

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan

      # - name: Terraform Apply (Disabled for PoC)
      #   run: terraform apply -auto-approve


